import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";

const faFont = localFont({
  src: [
    {
      path: "./../assets/fonts/IRANSansXFaNum-Regular.woff2",
    },
    {
      path: "./../assets/fonts/IRANSansXFaNum-Regular.woff",
    },
    {
      path: "./../assets/fonts/IRANSansXFaNum-Regular.ttf",
    },
  ],
  variable: "--font-fa",
});
export const metadata: Metadata = {
  title: "جمع سپاری",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" className={faFont.variable}>
      <body>{children}</body>
    </html>
  );
}
