import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.scss";
import clsx from "clsx";

const faFont = localFont({
  src: [
    {
      path: "./../assets/fonts/IRANSansXFaNum-Regular.woff2",
    },
    {
      path: "./../assets/fonts/IRANSansXFaNum-Regular.woff",
    },
    {
      path: "./../assets/fonts/IRANSansXFaNum-Regular.ttf",
    },
  ],
  variable: "--font-fa",
});

const rozhaFont = localFont({
  src: [
    {
      path: "./../assets/fonts/rozhaone-regular-webfont.woff2",
    },
    {
      path: "./../assets/fonts/rozhaone-regular-webfont.woff",
    },
  ],
  variable: "--rozha-fa",
});
export const metadata: Metadata = {
  title: "جمع سپاری",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={clsx(faFont.variable, rozhaFont.variable)}
    >
      <body>{children}</body>
    </html>
  );
}
