name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: pnpm i

      - name: Prettier
        run: pnpm prettier:check

      - name: Lint
        run: pnpm lint
